from salus.services.analytics.stats._dataclasses import (
    BootstrapCI,
    Correlation,
    EffectSize,
    EfficiencyResult,
    Fatigue,
    FDR,
    Forecast,
    HRV,
    OneRMResult,
    PI,
    Progression,
    RecoveryScore,
    Regression,
    SleepDebtResult,
    TrendTest,
)
from salus.services.analytics.stats._internal import (
    erf,
    incomplete_beta,
    ln_gamma,
    normal_cdf,
    normal_ppf,
    quantile,
    rank,
    t_cdf,
    t_ppf,
    xorshift64,
    yule_walker_ar1,
)
from salus.services.analytics.stats._stats import (
    covariance,
    mean,
    quantile_rank,
    rolling_mean,
    rolling_std,
    rolling_zscore,
    std,
    variance,
)
from salus.services.analytics.stats._regression import (
    linear_regression,
    prediction_interval,
)
from salus.services.analytics.stats._correlation import (
    cohens_d_paired,
    pearson,
    spearman,
)
from salus.services.analytics.stats._multiple import (
    benjamini_hochberg,
    mann_kendall,
)
from salus.services.analytics.stats._bootstrap import bootstrap_ci
from salus.services.analytics.stats._forecast import ewma_forecast, mape
from salus.services.analytics.stats._physiology import (
    hrv_time_domain,
    recovery_composite,
    resting_hr_windowed,
    rmssd_to_score,
    sleep_debt_cumulative,
    sleep_efficiency,
)
from salus.services.analytics.stats._metabolism import (
    bmr_cunningham,
    bmr_mifflin_st_jeor,
    hr_max_tanaka,
    hrr_pct,
    pal_from_hrr,
    tdee,
    tef_from_macros,
)
from salus.services.analytics.stats._workout import (
    brzycki_1rm,
    epley_1rm,
    fatigue_emwa,
    one_rm_regression,
    tonnage_progression,
)
from salus.services.analytics.stats._change_point import change_point_pelt

__all__ = [
    "benjamini_hochberg",
    "bmr_cunningham",
    "bmr_mifflin_st_jeor",
    "BootstrapCI",
    "bootstrap_ci",
    "brzycki_1rm",
    "change_point_pelt",
    "cohens_d_paired",
    "Correlation",
    "covariance",
    "EffectSize",
    "EfficiencyResult",
    "epley_1rm",
    "erf",
    "ewma_forecast",
    "fatigue_emwa",
    "Fatigue",
    "FDR",
    "FDR",
    "Forecast",
    "hr_max_tanaka",
    "hrr_pct",
    "HRV",
    "hrv_time_domain",
    "incomplete_beta",
    "linear_regression",
    "ln_gamma",
    "mann_kendall",
    "mape",
    "mean",
    "normal_cdf",
    "normal_ppf",
    "OneRMResult",
    "one_rm_regression",
    "pal_from_hrr",
    "pearson",
    "PI",
    "prediction_interval",
    "Progression",
    "quantile",
    "quantile_rank",
    "rank",
    "RecoveryScore",
    "recovery_composite",
    "Regression",
    "resting_hr_windowed",
    "rmssd_to_score",
    "rolling_mean",
    "rolling_std",
    "rolling_zscore",
    "SleepDebtResult",
    "sleep_debt_cumulative",
    "sleep_efficiency",
    "spearman",
    "std",
    "t_cdf",
    "t_ppf",
    "tdee",
    "tef_from_macros",
    "tonnage_progression",
    "TrendTest",
    "variance",
    "xorshift64",
    "yule_walker_ar1",
]
