"""add last_sync_at to sharing_relationship

Revision ID: 3f9a2e33ab15
Revises: 4b8c3f2d1a9e
Create Date: 2026-07-03 22:54:24.312074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9a2e33ab15'
down_revision: Union[str, Sequence[str], None] = '4b8c3f2d1a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharing_relationship', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sharing_relationship_api_token_hash'), 'sharing_relationship', ['api_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sharing_relationship_api_token_hash'), table_name='sharing_relationship')
    op.drop_column('sharing_relationship', 'last_sync_at')
    # ### end Alembic commands ###
