"""add_updated_at_and_deleted_at_to_all_user_scoped_tables

Revision ID: 42bde208c7ba
Revises: b3e7f1d9c2a0
Create Date: 2026-07-10 23:40:52.289960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bde208c7ba'
down_revision: Union[str, Sequence[str], None] = 'b3e7f1d9c2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asymmetric_share', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('asymmetric_share', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('circadian_profile', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('circadian_profile', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('circadian_profile', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('dashboard_widget', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('dashboard_widget', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('exercise', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('exercise', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('exercise', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('goal', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('goal', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('insight', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('insight', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leaderboard_group', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('leaderboard_group', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leaderboard_member', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('leaderboard_member', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('measurement', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('measurement', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('metric_type', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('metric_type', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('metric_type', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notification', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('notification', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('share_recipient', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('share_recipient', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sharing_relationship', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('workout_log_entry', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('workout_log_entry', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workout_log_entry', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('workout_plan', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('workout_plan_exercise', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('workout_plan_exercise', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workout_plan_exercise', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('workout_session', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('workout_session', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workout_session', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_session', 'deleted_at')
    op.drop_column('workout_session', 'updated_at')
    op.drop_column('workout_session', 'created_at')
    op.drop_column('workout_plan_exercise', 'deleted_at')
    op.drop_column('workout_plan_exercise', 'updated_at')
    op.drop_column('workout_plan_exercise', 'created_at')
    op.drop_column('workout_plan', 'deleted_at')
    op.drop_column('workout_log_entry', 'deleted_at')
    op.drop_column('workout_log_entry', 'updated_at')
    op.drop_column('workout_log_entry', 'created_at')
    op.drop_column('sharing_relationship', 'deleted_at')
    op.drop_column('share_recipient', 'deleted_at')
    op.drop_column('share_recipient', 'updated_at')
    op.drop_column('notification', 'deleted_at')
    op.drop_column('notification', 'updated_at')
    op.drop_column('metric_type', 'deleted_at')
    op.drop_column('metric_type', 'updated_at')
    op.drop_column('metric_type', 'created_at')
    op.drop_column('measurement', 'deleted_at')
    op.drop_column('measurement', 'updated_at')
    op.drop_column('leaderboard_member', 'deleted_at')
    op.drop_column('leaderboard_member', 'updated_at')
    op.drop_column('leaderboard_group', 'deleted_at')
    op.drop_column('leaderboard_group', 'updated_at')
    op.drop_column('insight', 'deleted_at')
    op.drop_column('insight', 'updated_at')
    op.drop_column('goal', 'deleted_at')
    op.drop_column('goal', 'updated_at')
    op.drop_column('exercise', 'deleted_at')
    op.drop_column('exercise', 'updated_at')
    op.drop_column('exercise', 'created_at')
    op.drop_column('dashboard_widget', 'deleted_at')
    op.drop_column('dashboard_widget', 'updated_at')
    op.drop_column('circadian_profile', 'deleted_at')
    op.drop_column('circadian_profile', 'updated_at')
    op.drop_column('circadian_profile', 'created_at')
    op.drop_column('asymmetric_share', 'deleted_at')
    op.drop_column('asymmetric_share', 'updated_at')
    # ### end Alembic commands ###
