"""add_updated_at_to_workout_plan

Revision ID: 5c4525ac71bb
Revises: eda62ce1cdd7
Create Date: 2026-07-08 15:37:13.105618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4525ac71bb'
down_revision: Union[str, Sequence[str], None] = 'eda62ce1cdd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plan', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plan', 'updated_at')
    # ### end Alembic commands ###
