"""add_position_to_metric_type

Revision ID: 626721e04f2c
Revises: 3f9a2e33ab15
Create Date: 2026-07-06 20:22:42.583626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626721e04f2c'
down_revision: Union[str, Sequence[str], None] = '3f9a2e33ab15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_type', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_type', 'position')
    # ### end Alembic commands ###
