"""add_circadian_profile_table

Revision ID: 79b1f2ae3ab4
Revises: 6675b4b3167d
Create Date: 2026-07-03 00:58:17.770342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79b1f2ae3ab4'
down_revision: Union[str, Sequence[str], None] = '6675b4b3167d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circadian_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone_offset_hours', sa.Float(), nullable=False),
    sa.Column('configured_chronotype', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circadian_profile_user_id'), 'circadian_profile', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circadian_profile_user_id'), table_name='circadian_profile')
    op.drop_table('circadian_profile')
    # ### end Alembic commands ###
