"""add_insight_table

Revision ID: 8f095e048e91
Revises: da8d032906ac
Create Date: 2026-07-01 23:46:29.183319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f095e048e91'
down_revision: Union[str, Sequence[str], None] = 'da8d032906ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_measurement_composite'), table_name='measurement')
    op.drop_index(op.f('idx_measurement_data_type'), table_name='measurement')
    op.drop_index(op.f('idx_measurement_ext_src'), table_name='measurement')
    op.drop_index(op.f('idx_measurement_external_id'), table_name='measurement')
    op.drop_index(op.f('idx_measurement_start_time'), table_name='measurement')
    op.drop_index(op.f('idx_measurement_user_id'), table_name='measurement')
    op.create_index(op.f('ix_measurement_data_type'), 'measurement', ['data_type'], unique=False)
    op.create_index(op.f('ix_measurement_external_id'), 'measurement', ['external_id'], unique=False)
    op.create_index(op.f('ix_measurement_start_time'), 'measurement', ['start_time'], unique=False)
    op.create_index(op.f('ix_measurement_user_id'), 'measurement', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_user_id'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_start_time'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_external_id'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_data_type'), table_name='measurement')
    op.create_index(op.f('idx_measurement_user_id'), 'measurement', ['user_id'], unique=False)
    op.create_index(op.f('idx_measurement_start_time'), 'measurement', ['start_time'], unique=False)
    op.create_index(op.f('idx_measurement_external_id'), 'measurement', ['external_id'], unique=False)
    op.create_index(op.f('idx_measurement_ext_src'), 'measurement', ['external_id', 'source'], unique=False)
    op.create_index(op.f('idx_measurement_data_type'), 'measurement', ['data_type'], unique=False)
    op.create_index(op.f('idx_measurement_composite'), 'measurement', ['user_id', 'data_type', 'start_time'], unique=False)
    # ### end Alembic commands ###
