"""decouple_dashboard_widgets

Revision ID: dc8084e23b07
Revises: 5fba86e6f14d
Create Date: 2026-07-16 17:35:00.833863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc8084e23b07'
down_revision: Union[str, Sequence[str], None] = '5fba86e6f14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_widget') as batch_op:
        batch_op.add_column(sa.Column('widget_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="metric"))
        batch_op.alter_column('metric_type_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_widget') as batch_op:
        batch_op.alter_column('metric_type_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('widget_type')
    # ### end Alembic commands ###
