"""add_position_to_workout_plan

Revision ID: eda62ce1cdd7
Revises: 626721e04f2c
Create Date: 2026-07-07 04:27:09.933036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda62ce1cdd7'
down_revision: Union[str, Sequence[str], None] = '626721e04f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plan', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plan', 'position')
    # ### end Alembic commands ###
