"""Add sharing relationship table

Revision ID: eee0b8202241
Revises: 6b647263d4a0
Create Date: 2026-07-02 11:18:54.047481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eee0b8202241'
down_revision: Union[str, Sequence[str], None] = '6b647263d4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_query_date'), 'insight', ['query_date'], unique=False)
    op.create_index(op.f('ix_insight_user_id'), 'insight', ['user_id'], unique=False)
    op.create_table('sharing_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('grantee_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('aggregation_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_type.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_data_type'), 'measurement', ['data_type'], unique=False)
    op.create_index(op.f('ix_measurement_external_id'), 'measurement', ['external_id'], unique=False)
    op.create_index(op.f('ix_measurement_start_time'), 'measurement', ['start_time'], unique=False)
    op.create_index(op.f('ix_measurement_user_id'), 'measurement', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_user_id'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_start_time'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_external_id'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_data_type'), table_name='measurement')
    op.drop_table('sharing_relationship')
    op.drop_index(op.f('ix_insight_user_id'), table_name='insight')
    op.drop_index(op.f('ix_insight_query_date'), table_name='insight')
    op.drop_table('insight')
    # ### end Alembic commands ###
