"""add leaderboard tables

Revision ID: ffa8baefa444
Revises: 79b1f2ae3ab4
Create Date: 2026-07-03 10:50:41.459657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffa8baefa444'
down_revision: Union[str, Sequence[str], None] = '79b1f2ae3ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('metric_type_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_frame', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_group_invite_code'), 'leaderboard_group', ['invite_code'], unique=True)
    op.create_index(op.f('ix_leaderboard_group_name'), 'leaderboard_group', ['name'], unique=False)
    op.create_table('leaderboard_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['leaderboard_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_member_user_handle'), 'leaderboard_member', ['user_handle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_member_user_handle'), table_name='leaderboard_member')
    op.drop_table('leaderboard_member')
    op.drop_index(op.f('ix_leaderboard_group_name'), table_name='leaderboard_group')
    op.drop_index(op.f('ix_leaderboard_group_invite_code'), table_name='leaderboard_group')
    op.drop_table('leaderboard_group')
    # ### end Alembic commands ###
