"""Standard reference exercises seeded on system startup.

Shared across all users (user_id=None, shared_nullable strategy).
Uses canonical anatomical muscle keys for exact 2D vector heatmap mapping.
"""

COMMON_EXERCISES: list[dict] = [
    # ── Brust / Chest ──
    {
        "id": "ex-bench-press-barbell",
        "name": "Bankdrücken (Langhantel)",
        "equipment": "barbell",
        "primary_muscles": "chest_sternal",
        "secondary_muscles": "triceps_lateral, deltoid_anterior",
        "description": "Klassische Grundübung zur Maximierung von Brust- und Oberkörperkraft.",
        "instructions": "Flach auf die Bank legen, Schulterblätter fixieren, Hantel kontrolliert zur unteren Brust absenken und kraftvoll nach oben drücken.",
        "suggested_rest_seconds": 180,
    },
    {
        "id": "ex-incline-bench-press-dumbbell",
        "name": "Schrägbankdrücken (Kurzhantel)",
        "equipment": "dumbbell",
        "primary_muscles": "chest_clavicular",
        "secondary_muscles": "deltoid_anterior, triceps_lateral",
        "description": "Fokus auf die klavikulären Fasern der oberen Brustmuskulatur.",
        "instructions": "Bank auf ca. 30° einstellen. Kurzhanteln kontrolliert absenken und über der Brust zusammenführen.",
        "suggested_rest_seconds": 120,
    },
    {
        "id": "ex-dips-chest",
        "name": "Dips (Brustfokus)",
        "equipment": "bodyweight",
        "primary_muscles": "chest_sternal",
        "secondary_muscles": "triceps_long, deltoid_anterior",
        "description": "Körpergewichts- oder Zusatzgewichtsübung für untere Brust und Trizeps.",
        "instructions": "Leicht nach vorne beugen, Ellbogen nach außen führen und bis ca. 90° Beugung kontrolliert absenken.",
        "suggested_rest_seconds": 120,
    },
    {
        "id": "ex-cable-flys",
        "name": "Kabelzug-Flys (Fliegende)",
        "equipment": "cable",
        "primary_muscles": "chest_sternal, chest_clavicular",
        "secondary_muscles": "deltoid_anterior",
        "description": "Isolationsübung mit kontinuierlicher Muskelspannung über den gesamten Bewegungsumfang.",
        "instructions": "Arme leicht gebeugt halten und die Griffe vor dem Körper zusammenführen, Spitzenkontraktion halten.",
        "suggested_rest_seconds": 90,
    },

    # ── Rücken / Back ──
    {
        "id": "ex-deadlift-conventional",
        "name": "Kreuzheben (Konventionell)",
        "equipment": "barbell",
        "primary_muscles": "erector_spinae, gluteus_maximus, hamstrings",
        "secondary_muscles": "quadriceps, trapezius_upper, forearms",
        "description": "Ganzkörper-Grundübung zur Kräftigung der gesamten posterioren Kette.",
        "instructions": "Hüftbreiter Stand, gerader Rücken, Stange eng am Körper nach oben ziehen und die Hüfte strecken.",
        "suggested_rest_seconds": 180,
    },
    {
        "id": "ex-pullups",
        "name": "Klimmzüge (Pull-ups)",
        "equipment": "bodyweight",
        "primary_muscles": "latissimus_dorsi, trapezius_mid_lower",
        "secondary_muscles": "biceps_brachii, forearms",
        "description": "Vertikale Zugübung für den Latissimus Dorsi und oberen Rücken.",
        "instructions": "Im Obergriff hängen, Schulterblätter nach unten ziehen und bis zum Kinn über der Stange hochziehen.",
        "suggested_rest_seconds": 120,
    },
    {
        "id": "ex-bent-over-row-barbell",
        "name": "Langhantelrudern vorgebeugt",
        "equipment": "barbell",
        "primary_muscles": "latissimus_dorsi, rhomboids, trapezius_mid_lower",
        "secondary_muscles": "biceps_brachii, deltoid_posterior",
        "description": "Horizontale Zugübung für Latissimus, Trapez und Romboiden.",
        "instructions": "Oberkörper ca. 45° nach vorne neigen, Stange zum Bauchnabel ziehen und Schulterblätter kontrahieren.",
        "suggested_rest_seconds": 120,
    },
    {
        "id": "ex-lat-pulldown",
        "name": "Latzug zur Brust",
        "equipment": "cable",
        "primary_muscles": "latissimus_dorsi",
        "secondary_muscles": "biceps_brachii, trapezius_mid_lower",
        "description": "Geführte vertikale Zugübung zur Hypertrophie des Latissimus.",
        "instructions": "Stange kontrolliert zum oberen Brustbein ziehen, leichte Rücklage beibehalten.",
        "suggested_rest_seconds": 90,
    },

    # ── Beine / Legs ──
    {
        "id": "ex-squats-high-bar",
        "name": "Kniebeugen (High Bar)",
        "equipment": "barbell",
        "primary_muscles": "quadriceps, gluteus_maximus",
        "secondary_muscles": "adductors, rectus_abdominis, erector_spinae",
        "description": "Die Königsübung für Quadrizeps- und Unterkörperentwicklung.",
        "instructions": "Schulterbreiter Stand, Stange auf oberem Trapez. Tief absenken (unter 90°) und kraftvoll aufstehen.",
        "suggested_rest_seconds": 180,
    },
    {
        "id": "ex-romanian-deadlift",
        "name": "Rumänisches Kreuzheben (RDL)",
        "equipment": "barbell",
        "primary_muscles": "hamstrings, gluteus_maximus",
        "secondary_muscles": "erector_spinae, trapezius_upper",
        "description": "Hüftdominante Dehnungsübung für Beinbeuger und Gesäß.",
        "instructions": "Knie leicht gebeugt halten, Hüfte weit nach hinten schieben und Oberkörper nach vorne neigen.",
        "suggested_rest_seconds": 120,
    },
    {
        "id": "ex-leg-press-45",
        "name": "Beinpresse 45°",
        "equipment": "machine",
        "primary_muscles": "quadriceps",
        "secondary_muscles": "gluteus_maximus, adductors",
        "description": "Maschinengestützte Belastung mit maximaler Stabilität.",
        "instructions": "Füße mittig auf der Plattform platzieren, bis 90° Beugung absenken, Knie nicht durchdrücken.",
        "suggested_rest_seconds": 120,
    },
    {
        "id": "ex-leg-curls-seated",
        "name": "Beinbeuger (Sitzend)",
        "equipment": "machine",
        "primary_muscles": "hamstrings",
        "secondary_muscles": "gastrocnemius",
        "description": "Isolierte Hypertrophieübung für die ischiokrurale Muskulatur.",
        "instructions": "Polster an den Fersen anlegen, Beine kontrolliert beugen und 1 Sekunde halten.",
        "suggested_rest_seconds": 90,
    },
    {
        "id": "ex-calf-raises-standing",
        "name": "Wadenheben (Stehend)",
        "equipment": "machine",
        "primary_muscles": "gastrocnemius",
        "secondary_muscles": "soleus, tibialis_anterior",
        "description": "Gastrocnemius- und Soleus-Entwicklung durch volle Dehnung.",
        "instructions": "Fersen tief absenken für maximale Dehnung, dann maximal auf die Zehenspitzen drücken.",
        "suggested_rest_seconds": 60,
    },

    # ── Schultern / Shoulders ──
    {
        "id": "ex-overhead-press-barbell",
        "name": "Schulterdrücken (Overhead Press)",
        "equipment": "barbell",
        "primary_muscles": "deltoid_anterior, deltoid_lateral",
        "secondary_muscles": "triceps_lateral, trapezius_upper, rectus_abdominis",
        "description": "Vertikales Drücken über Kopf im Stehen.",
        "instructions": "Stange auf Schultern ablegen, Bauch fest anspannen und Stange senkrecht nach oben drücken.",
        "suggested_rest_seconds": 150,
    },
    {
        "id": "ex-lateral-raises-cable",
        "name": "Seitheben am Kabelzug",
        "equipment": "cable",
        "primary_muscles": "deltoid_lateral",
        "secondary_muscles": "trapezius_upper",
        "description": "Isolationsübung für den lateralen Deltamuskel (Schulterbreite).",
        "instructions": "Kabel seitlich hochziehen bis Schulterhöhe, Daumen leicht nach unten.",
        "suggested_rest_seconds": 75,
    },
    {
        "id": "ex-face-pulls",
        "name": "Face Pulls",
        "equipment": "cable",
        "primary_muscles": "deltoid_posterior, trapezius_mid_lower",
        "secondary_muscles": "rhomboids, trapezius_upper",
        "description": "Haltungskorrektur und Stärkung der Außenrotatoren und hinteren Schultern.",
        "instructions": "Seil zum Gesicht ziehen, Ellbogen hoch und nach außen halten, Hände nach hinten rotieren.",
        "suggested_rest_seconds": 60,
    },

    # ── Arme / Arms ──
    {
        "id": "ex-biceps-curls-dumbbell",
        "name": "Bizepscurls (Kurzhantel)",
        "equipment": "dumbbell",
        "primary_muscles": "biceps_brachii",
        "secondary_muscles": "forearms",
        "description": "Klassische Supinationscurls für Bizepshöhe und Unterarme.",
        "instructions": "Ellbogen nah am Körper fixieren, Hantel beugen und im oberen Drittel supinieren.",
        "suggested_rest_seconds": 75,
    },
    {
        "id": "ex-triceps-pushdown-rope",
        "name": "Trizepsdrücken am Kabelzug (Seil)",
        "equipment": "cable",
        "primary_muscles": "triceps_lateral, triceps_long",
        "secondary_muscles": "forearms",
        "description": "Isolierte Trizeps-Streckung für den lateralen und medialen Kopf.",
        "instructions": "Ellbogen fixieren, Seil nach unten drücken und am Endpunkt auseinanderziehen.",
        "suggested_rest_seconds": 75,
    },

    # ── Core & Bauch ──
    {
        "id": "ex-hanging-leg-raises",
        "name": "Hängendes Beinheben",
        "equipment": "bodyweight",
        "primary_muscles": "rectus_abdominis",
        "secondary_muscles": "obliques, forearms",
        "description": "Intensive Rumpfübung zur Kräftigung der unteren Bauchmuskeln.",
        "instructions": "An der Klimmzugstange hängen, Beine gestreckt oder gebeugt anheben und Becken einrollen.",
        "suggested_rest_seconds": 90,
    },
    {
        "id": "ex-cable-woodchoppers",
        "name": "Kabelzug-Rotationsdrücken (Woodchopper)",
        "equipment": "cable",
        "primary_muscles": "obliques, rectus_abdominis",
        "secondary_muscles": "deltoid_anterior, serratus_anterior",
        "description": "Anti-Rotations- und Rotationskraft für die schrägen Bauchmuskeln.",
        "instructions": "Diagonal über den Rumpf rotieren, Bewegung aus der Körpermitte steuern.",
        "suggested_rest_seconds": 60,
    },
]
