ACHIEVEMENT_DEFINITIONS: list[dict] = [
    {
        "code": "first_entry",
        "title": "Der erste Schritt",
        "description": "Deinen ersten Gesundheitswert eingetragen.",
        "icon": "edit-note",
        "tier": "bronze",
        "category": "tracking",
        "condition_type": "count",
        "condition_config": '{"entity": "measurement", "op": "gte", "value": 1}',
        "is_hidden": False,
        "sort_order": 1,
    },
    {
        "code": "entries_10",
        "title": "Regelmäßig",
        "description": "10 Einträge geloggt.",
        "icon": "sort",
        "tier": "bronze",
        "category": "milestone",
        "condition_type": "count",
        "condition_config": '{"entity": "measurement", "op": "gte", "value": 10}',
        "is_hidden": False,
        "sort_order": 2,
    },
    {
        "code": "entries_100",
        "title": "Datenliebhaber",
        "description": "100 Einträge geloggt.",
        "icon": "bar-chart",
        "tier": "silver",
        "category": "milestone",
        "condition_type": "count",
        "condition_config": '{"entity": "measurement", "op": "gte", "value": 100}',
        "is_hidden": False,
        "sort_order": 3,
    },
    {
        "code": "entries_1000",
        "title": "Daten-Veteran",
        "description": "1.000 Einträge geloggt.",
        "icon": "analytics",
        "tier": "gold",
        "category": "milestone",
        "condition_type": "count",
        "condition_config": '{"entity": "measurement", "op": "gte", "value": 1000}',
        "is_hidden": False,
        "sort_order": 4,
    },
    {
        "code": "first_habit",
        "title": "Gewohnheitstier",
        "description": "Deinen ersten Habit erstellt.",
        "icon": "check-circle",
        "tier": "bronze",
        "category": "habit",
        "condition_type": "count",
        "condition_config": '{"entity": "habit", "op": "gte", "value": 1}',
        "is_hidden": False,
        "sort_order": 10,
    },
    {
        "code": "tracking_7_day",
        "title": "Eine Woche am Ball",
        "description": "7 Tage in Folge mindestens einen Wert getrackt.",
        "icon": "local-fire-department",
        "tier": "bronze",
        "category": "streak",
        "condition_type": "streak",
        "condition_config": '{"entity": "measurement", "days": 7}',
        "is_hidden": False,
        "sort_order": 20,
    },
    {
        "code": "tracking_30_day",
        "title": "Monats-Marathon",
        "description": "30 Tage in Folge getrackt.",
        "icon": "local-fire-department",
        "tier": "silver",
        "category": "streak",
        "condition_type": "streak",
        "condition_config": '{"entity": "measurement", "days": 30}',
        "is_hidden": False,
        "sort_order": 21,
    },
    {
        "code": "tracking_90_day",
        "title": "Quartals-König",
        "description": "90 Tage in Folge getrackt.",
        "icon": "local-fire-department",
        "tier": "gold",
        "category": "streak",
        "condition_type": "streak",
        "condition_config": '{"entity": "measurement", "days": 90}',
        "is_hidden": False,
        "sort_order": 22,
    },
    {
        "code": "tracking_365_day",
        "title": "Jahresring",
        "description": "365 Tage in Folge getrackt. Unglaublich!",
        "icon": "whatshot",
        "tier": "platinum",
        "category": "streak",
        "condition_type": "streak",
        "condition_config": '{"entity": "measurement", "days": 365}',
        "is_hidden": False,
        "sort_order": 23,
    },
    {
        "code": "habit_7_day",
        "title": "Habit-Woche",
        "description": "Einen Habit 7 Tage in Folge abgeschlossen.",
        "icon": "check-circle",
        "tier": "bronze",
        "category": "habit",
        "condition_type": "streak",
        "condition_config": '{"entity": "habit_log", "days": 7}',
        "is_hidden": False,
        "sort_order": 30,
    },
    {
        "code": "habit_30_day",
        "title": "Habit-Monat",
        "description": "Einen Habit 30 Tage in Folge abgeschlossen.",
        "icon": "check-circle",
        "tier": "silver",
        "category": "habit",
        "condition_type": "streak",
        "condition_config": '{"entity": "habit_log", "days": 30}',
        "is_hidden": False,
        "sort_order": 31,
    },
    {
        "code": "habit_90_day",
        "title": "Habit-Meister",
        "description": "Einen Habit 90 Tage in Folge abgeschlossen.",
        "icon": "check-circle",
        "tier": "gold",
        "category": "habit",
        "condition_type": "streak",
        "condition_config": '{"entity": "habit_log", "days": 90}',
        "is_hidden": False,
        "sort_order": 32,
    },
    {
        "code": "mood_7_day",
        "title": "Gefühls-Tagebuch",
        "description": "7 Tage in Folge deine Stimmung geloggt.",
        "icon": "sentiment-satisfied",
        "tier": "bronze",
        "category": "streak",
        "condition_type": "streak",
        "condition_config": '{"entity": "mood_entry", "days": 7}',
        "is_hidden": False,
        "sort_order": 40,
    },
    {
        "code": "mood_30_day",
        "title": "Emotionale Achtsamkeit",
        "description": "30 Tage in Folge deine Stimmung geloggt.",
        "icon": "psychology",
        "tier": "silver",
        "category": "streak",
        "condition_type": "streak",
        "condition_config": '{"entity": "mood_entry", "days": 30}',
        "is_hidden": False,
        "sort_order": 41,
    },
    {
        "code": "first_goal",
        "title": "Zielstrebig",
        "description": "Dein erstes Ziel gesetzt.",
        "icon": "flag",
        "tier": "bronze",
        "category": "goal",
        "condition_type": "count",
        "condition_config": '{"entity": "goal", "op": "gte", "value": 1}',
        "is_hidden": False,
        "sort_order": 50,
    },
    {
        "code": "goal_achieved_1",
        "title": "Ziel erreicht",
        "description": "Ein Ziel erfolgreich abgeschlossen.",
        "icon": "verified",
        "tier": "silver",
        "category": "goal",
        "condition_type": "count",
        "condition_config": '{"entity": "goal", "op": "gte", "value": 1, "state": "achieved"}',
        "is_hidden": False,
        "sort_order": 51,
    },
    {
        "code": "first_workout",
        "title": "Eiserner Wille",
        "description": "Dein erstes Workout abgeschlossen.",
        "icon": "fitness-center",
        "tier": "bronze",
        "category": "workout",
        "condition_type": "count",
        "condition_config": '{"entity": "workout_session", "op": "gte", "value": 1}',
        "is_hidden": False,
        "sort_order": 60,
    },
    {
        "code": "workouts_10",
        "title": "Trainings-Tier",
        "description": "10 Workouts abgeschlossen.",
        "icon": "fitness-center",
        "tier": "silver",
        "category": "workout",
        "condition_type": "count",
        "condition_config": '{"entity": "workout_session", "op": "gte", "value": 10}',
        "is_hidden": False,
        "sort_order": 61,
    },
    {
        "code": "workouts_50",
        "title": "Kraftpaket",
        "description": "50 Workouts abgeschlossen.",
        "icon": "fitness-center",
        "tier": "gold",
        "category": "workout",
        "condition_type": "count",
        "condition_config": '{"entity": "workout_session", "op": "gte", "value": 50}',
        "is_hidden": False,
        "sort_order": 62,
    },
    {
        "code": "first_share",
        "title": "Teamplayer",
        "description": "Zum ersten Mal Daten geteilt.",
        "icon": "share",
        "tier": "bronze",
        "category": "social",
        "condition_type": "count",
        "condition_config": '{"entity": "sharing_relationship", "op": "gte", "value": 1}',
        "is_hidden": False,
        "sort_order": 70,
    },
    {
        "code": "early_bird",
        "title": "Frühaufsteher",
        "description": "Vor 6 Uhr morgens einen Wert eingetragen.",
        "icon": "wb-twilight",
        "tier": "silver",
        "category": "special",
        "condition_type": "count",
        "condition_config": '{"entity": "measurement", "op": "gte", "value": 1, "hour_before": 6}',
        "is_hidden": True,
        "sort_order": 80,
    },
    {
        "code": "night_owl_tracker",
        "title": "Nachteule",
        "description": "Nach Mitternacht noch getrackt.",
        "icon": "dark-mode",
        "tier": "silver",
        "category": "special",
        "condition_type": "count",
        "condition_config": '{"entity": "measurement", "op": "gte", "value": 1, "hour_after": 0, "hour_before": 4}',
        "is_hidden": True,
        "sort_order": 81,
    },
    {
        "code": "perfect_week",
        "title": "Perfekte Woche",
        "description": "Jeden Tag mindestens einen Eintrag, einen Habit und ein Workout.",
        "icon": "auto-awesome",
        "tier": "gold",
        "category": "special",
        "condition_type": "compound",
        "condition_config": '{"op": "and", "conditions": ['
        '{"type": "streak", "entity": "measurement", "days": 7},'
        '{"type": "streak", "entity": "habit_log", "days": 7},'
        '{"type": "count", "entity": "workout_session", "op": "gte", "value": 1, "within_days": 7}'
        ']}',
        "is_hidden": True,
        "sort_order": 82,
    },
    {
        "code": "data_donor",
        "title": "Wissenschafts-Spender",
        "description": "Daten an Open Science gespendet.",
        "icon": "science",
        "tier": "gold",
        "category": "special",
        "condition_type": "count",
        "condition_config": '{"entity": "open_science_consent", "op": "gte", "value": 1}',
        "is_hidden": False,
        "sort_order": 83,
    },
]
